/*
 * data_tables.h
 *
 *  Created on: Dec 3, 2009
 *      Author: Chase
 */

#pragma once
#ifndef __DATA_TABLES_H__
#define __DATA_TABLES_H__

#include <stdint.h>

namespace PokeLib {
	const char *nature[] = {
		"Hardy","Lonely","Brave","Adamant","Naughty",
		"Bold","Docile","Relaxed","Impish","Lax",
		"Timid","Hasty","Serious","Jolly","Naive",
		"Modest","Mild","Quiet","Bashful","Rash",
		"Calm","Gentle","Sassy","Careful","Quirk",
	};

	const char *ability[] = {
		"No Ability","Stench","Drizzle","Speed Boost","Battle Armor","Sturdy",
		"Damp","Limber","Sand Veil","Static","Volt Absorb","Water Absorb",
		"Oblivious","Cloud Nine","Compoundeyes","Insomnia","Color Change","Immunity",
		"Flash Fire","Shield Dust","Own Tempo","Suction Cups","Intimidate","Shadow Tag",
		"Rough Skin","Wonder Guard","Levitate","Effect Spore","Synchronize","Clear Body",
		"Natural Cure","Lightningrod","Serene Grace","Swift Swim","Chlorophyll","Illuminate",
		"Trace","Huge Power","Poison Point","Inner Focus","Magma Armor","Water Veil",
		"Magnet Pull","Soundproof","Rain Dish","Sand Stream","Pressure","Thick Fat",
		"Early Bird","Flame Body","Run Away","Keen Eye","Hyper Cutter","Pickup",
		"Truant","Hustle","Cute Charm","Plus","Minus","Forecast",
		"Sticky Hold","Shed Skin","Guts","Marvel Scale","Liquid Ooze","Overgrow",
		"Blaze","Torrent","Swarm","Rock Head","Drought","Arena Trap",
		"Vital Spirit","White Smoke","Pure Power","Shell Armor","Air Lock","Tangled Feet",
		"Motor Drive","Rivalry","Steadfast","Snow Cloak","Gluttony","Anger Point",
		"Unburden","Heat Proof","Simple","Dry Skin","Download","Iron Fist",
		"Poison Heal","Adaptability","Skill Link","Hydration","Solar Power","Quick Feet",
		"Normalize","Sniper","Magic Guard","No Guard","Stall","Technician",
		"Leaf Guard","Klutz","Mold Breaker","Super Luck","Aftermath","Anticipation",
		"Forewarn","Unaware","Tinted Lens","Filter","Slow Start","Scrappy",
		"Storm Drain","Ice Body","Solid Rock","Snow Warning","Honey Gather","Frisk",
		"Reckless","Multitype","Flower Gift","Bad Dreams"
	};

	const char *items[] = {"----",
		"Master Ball","Ultra Ball","Great Ball","Poke Ball",
		"Safari Ball","Net Ball","Dive Ball","Nest Ball",
		"Repeat Ball","Timer Ball","Luxury Ball","Premier Ball",
		"Dusk Ball","Heal Ball","Quick Ball","Cherish Ball",
		"Potion","Antidote","Burn Heal","Ice Heal",
		"Awakening","Parlyz Heal","Full Restore","Max Potion",
		"Hyper Potion","Super Potion","Full Heal","Revive",
		"Max Revive","Fresh Water","Soda Pop","Lemonade",
		"Moomoo Milk","EnergyPowder","Energy Root","Heal Powder",
		"Revival Herb","Ether","Max Ether","Elixir",
		"Max Elixir","Lava Cookie","Berry Juice","Sacred Ash",
		"HP Up","Protein","Iron","Carbos",
		"Calcium","Rare Candy","PP Up","Zinc",
		"PP Max","Old Gateau","Guard Spec.","Dire Hit",
		"X Attack","X Defend","X Speed","X Accuracy",
		"X Special","X Sp. Def","Poke Doll","Fluffy Tail",
		"Blue Flute","Yellow Flute","Red Flute","Black Flute",
		"White Flute","Shoal Salt","Shoal Shell","Red Shard",
		"Blue Shard","Yellow Shard","Green Shard","Super Repel",
		"Max Repel","Escape Rope","Repel","Sun Stone",
		"Moon Stone","Fire Stone","Thunderstone","Water Stone",
		"Leaf Stone","TinyMushroom","Big Mushroom","Pearl",
		"Big Pearl","Stardust","Star Piece","Nugget",
		"Heart Scale","Honey","Growth Mulch","Damp Mulch",
		"Stable Mulch","Gooey Mulch","Root Fossil","Claw Fossil",
		"Helix Fossil","Dome Fossil","Old Amber","Armor Fossil",
		"Skull Fossil","Rare Bone","Shiny Stone","Dusk Stone",
		"Dawn Stone","Oval Stone","Odd Keystone","Griseous Orb",
		"???","???","???","???","???","???","???","???","???","???",
		"???","???","???","???","???","???","???","???","???","???",
		"???","???","Adamant Orb","Lustrous Orb",
		"Grass Mail","Flame Mail","Bubble Mail","Bloom Mail",
		"Tunnel Mail","Steel Mail","Heart Mail","Snow Mail",
		"Space Mail","Air Mail","Mosaic Mail","Brick Mail",
		"Cheri Berry","Chesto Berry","Pecha Berry","Rawst Berry",
		"Aspear Berry","Leppa Berry","Oran Berry","Persim Berry",
		"Lum Berry","Sitrus Berry","Figy Berry","Wiki Berry",
		"Mago Berry","Aguav Berry","Iapapa Berry","Razz Berry",
		"Bluk Berry","Nanab Berry","Wepear Berry","Pinap Berry",
		"Pomeg Berry","Kelpsy Berry","Qualot Berry","Hondew Berry",
		"Grepa Berry","Tamato Berry","Cornn Berry","Magost Berry",
		"Rabuta Berry","Nomel Berry","Spelon Berry","Pamtre Berry",
		"Watmel Berry","Durin Berry","Belue Berry","Occa Berry",
		"Passho Berry","Wacan Berry","Rindo Berry","Yache Berry",
		"Chople Berry","Kebia Berry","Shuca Berry","Coba Berry",
		"Payapa Berry","Tanga Berry","Charti Berry","Kasib Berry",
		"Haban Berry","Colbur Berry","Babiri Berry","Chilan Berry",
		"Liechi Berry","Ganlon Berry","Salac Berry","Petaya Berry",
		"Apicot Berry","Lansat Berry","Starf Berry","Enigma Berry",
		"Micle Berry","Custap Berry","Jaboca Berry","Rowap Berry",
		"BrightPowder","White Herb","Macho Brace","Exp. Share",
		"Quick Claw","Soothe Bell","Mental Herb","Choice Band",
		"King's Rock","SilverPowder","Amulet Coin","Cleanse Tag",
		"Soul Dew","DeepSeaTooth","DeepSeaScale","Smoke Ball",
		"Everstone","Focus Band","Lucky Egg","Scope Lens",
		"Metal Coat","Leftovers","Dragon Scale","Light Ball",
		"Soft Sand","Hard Stone","Miracle Seed","BlackGlasses",
		"Black Belt","Magnet","Mystic Water","Sharp Beak",
		"Poison Barb","NeverMeltIce","Spell Tag","TwistedSpoon",
		"Charcoal","Dragon Fang","Silk Scarf","Up-Grade",
		"Shell Bell","Sea Incense","Lax Incense","Lucky Punch",
		"Metal Powder","Thick Club","Stick","Red Scarf",
		"Blue Scarf","Pink Scarf","Green Scarf","Yellow Scarf",
		"Wide Lens","Muscle Band","Wise Glasses","Expert Belt",
		"Light Clay","Life Orb","Power Herb","Toxic Orb",
		"Flame Orb","Quick Powder","Focus Sash","Zoom Lens",
		"Metronome","Iron Ball","Lagging Tail","Destiny Knot",
		"Black Sludge","Icy Rock","Smooth Rock","Heat Rock",
		"Damp Rock","Grip Claw","Choice Scarf","Sticky Barb",
		"Power Bracer","Power Belt","Power Lens","Power Band",
		"Power Anklet","Power Weight","Shed Shell","Big Root",
		"Choice Specs","Flame Plate","Splash Plate","Zap Plate",
		"Meadow Plate","Icicle Plate","Fist Plate","Toxic Plate",
		"Earth Plate","Sky Plate","Mind Plate","Insect Plate",
		"Stone Plate","Spooky Plate","Draco Plate","Dread Plate",
		"Iron Plate","Odd Incense","Rock Incense","Full Incense",
		"Wave Incense","Rose Incense","Luck Incense","Pure Incense",
		"Protector","Electirizer","Magmarizer","Dubious Disc",
		"Reaper Cloth","Razor Claw","Razor Fang","TM01",
		"TM02","TM03","TM04","TM05","TM06","TM07","TM08","TM09",
		"TM10","TM11","TM12","TM13","TM14","TM15","TM16","TM17",
		"TM18","TM19","TM20","TM21","TM22","TM23","TM24","TM25",
		"TM26","TM27","TM28","TM29","TM30","TM31","TM32","TM33",
		"TM34","TM35","TM36","TM37","TM38","TM39","TM40","TM41",
		"TM42","TM43","TM44","TM45","TM46","TM47","TM48","TM49",
		"TM50","TM51","TM52","TM53","TM54","TM55","TM56","TM57",
		"TM58","TM59","TM60","TM61","TM62","TM63","TM64","TM65",
		"TM66","TM67","TM68","TM69","TM70","TM71","TM72","TM73",
		"TM74","TM75","TM76","TM77","TM78","TM79","TM80","TM81",
		"TM82","TM83","TM84","TM85","TM86","TM87","TM88","TM89",
		"TM90","TM91","TM92","HM01","HM02","HM03","HM04","HM05",
		"HM06","HM07","HM08","Explorer Kit",
		"Loot Sack","Rule Book","Poke Radar","Point Card",
		"Journal","Seal Case","Fashion Case","Seal Bag",
		"Pal Pad","Works Key","Old Charm","Galactic Key",
		"Red Chain","Town Map","Vs. Seeker","Coin Case",
		"Old Rod","Good Rod","Super Rod","Sprayduck",
		"Poffin Case","Bicycle","Suite Key","Oak's Letter",
		"Lunar Wing","Member Card","Azure Flute","S.S. Ticket",
		"Contest Pass","Magma Stone","Parcel","Coupon 1",
		"Coupon 2","Coupon 3","Storage Key","SecretPotion",
		"Vs. Recorder", "Gracidea", "Secret Key",
		//HG/SS
		"Apricorn Case","Unown Note","Berry Planter",
		"Itemfinder","Blue Card","Slowpoketail",
		"Clear Bell","Card Key","Basement Key",
		"Squirtbottle","Red Scale","Lost Item",
		"Magnet Pass","Machine Part","Silver Wing",
		"Rainbow Wing","Mystery Egg","Red Apricorn",
		"Yellow Apricorn","Blue Apricorn","Green Apricorn",
		"Pink Apricorn","White Apricorn","Black Apricorn",
		"Fast Ball","Level Ball","Lure Ball","Heavy Ball",
		"Love Ball","Friend Ball","Moon Ball","Compe Ball",
		"Park Ball","Photo Album","GB Player","Tide Bell",
		"Rage Candy Bar","Data Card 01","Data Card 02",
		"Data Card 03","Data Card 04","Data Card 05",
		"Data Card 06","Data Card 07","Data Card 08",
		"Data Card 09","Data Card 10","Data Card 11",
		"Data Card 12","Data Card 13","Data Card 14",
		"Data Card 15","Data Card 16","Data Card 17",
		"Data Card 18","Data Card 19","Data Card 20",
		"Data Card 21","Data Card 22","Data Card 23",
		"Data Card 24","Data Card 25","Data Card 26",
		"Data Card 27","Green Orb","Capsule Lock",
		"Red Orb","Blue Orb","Mystery Crystal"
	};

	const char *hometown[] = {
		"Unknown","Hoenn (Sapphire)","Hoenn (Ruby)",
		"Hoenn (Emerald)","Kanto (FireRed)","Kanto (LeafGreen)","???",
		"Johto (Gold)","Johto (Silver)","???","Sinnoh (Diamond)",
		"Sinnoh (Pearl)","Sinnoh (Platinum)","???","???","Colosseum"
	};

	//base locations
	const char *location_0x0000[] = {
		"Mystery Zone","Twinleaf Town","Sandgem Town",
		"Floaroma Town","Solaceon Town","Celestic Town",
		"Jubilife City","Canalave City","Oreburgh City",
		"Eterna City","Hearthome City","Pastoria City",
		"Veilstone City","Sunyshore City","Snowpoint City",
		"Pokemon League","Route 201","Route 202",
		"Route 203","Route 204","Route 205",
		"Route 206","Route 207","Route 208",
		"Route 209","Route 210","Route 211",
		"Route 212","Route 213","Route 214",
		"Route 215","Route 216","Route 217",
		"Route 218","Route 219","Route 220",
		"Route 221","Route 222","Route 223",
		"Route 224","Route 225","Route 226",
		"Route 227","Route 228","Route 229",
		"Route 230","Oreburgh Mine","Valley Windworks",
		"Eterna Forest","Fuego Ironworks","Mt. Coronet",
		"Spear Pillar","Great Marsh","Solaceon Ruins",
		"Victory Road","Pal Park","Amity Square",
		"Ravaged Path","Floaroma Meadow","Oreburgh Gate",
		"Fullmoon Island","Sendoff Spring","Turnback Cave",
		"Flower Paradise","Snowpoint Temple","Wayward Cave",
		"Ruin Maniac Cave","Maniac Tunnel","Trophy Garden",
		"Iron Island","Old Chateau","Galactic HQ",
		"Verity Lakefront","Valor Lakefront","Acuity Lakefront",
		"Spring Path","Lake Verity","Lake Valor",
		"Lake Acuity","Newmoon Island","Battle Tower",
		"Fight Area","Survival Area","Resort Area",
		"Stark Mountain","Seabreak Path","Hall of Origin",
		"Verity Cavern","Valor Cavern","Acuity Cavern",
		"Jubilife TV","Poketch Co.","GTS",
		"Trainer's School","Mining Museum","Flower Shop",
		"Cycle Shop","Contest Hall","Poffin House",
		"Foreign Building", "Pokemon Day Care","Veilstone Store",
		"Game Corner","Canalave Library","Vista Lighthouse",
		"Sunyshore Market","Pokemon Mansion","Footstep House",
		"Cafe","Grand Lake","Restaurant","Battle Park",
		"Battle Frontier","Battle Factory","Battle Castle",
		"Battle Arcade","Battle Hall","Distortion World",
		"Global Terminal","Villa","Battleground",
		"ROTOM's Room","T.G. Eterna Bldg","Iron Ruins",
		"Iceberg Ruins","Rock Peak Ruins"
	};

	const char *location_0x2000[] = { //20xx
		"Day-Care Couple",
		"Link trade (arrive)",
		"Link trade (met)",
		"Kanto","Johto","Hoenn",
		"Sinnoh","Distant land",
		"Traveling Man","Riley",
		"Cynthia","Mystery Zone"
	};

	//30xx
	const char *location_0x3000[] = { //30xx
		"Lovely Place","Pokemon Ranger","Faraway Place",
		"Pokemon Movie","Pokemon Movie 06","Pokemon Movie 07",
		"Pokemon Movie 08","Pokemon Movie 09","Pokemon Movie 10",
		"Pokemon Movie 11","Pokemon Movie 12","Pokemon Movie 13",
		"Pokemon Movie 14","Pokemon Movie 15","Pokemon Movie 16",
		"Pokemon Cartoon","Space World","Space World 06",
		"Space World 07","Space World 08","Space World 09",
		"Space World 10","Space World 11","Space World 12",
		"Space World 13","Space World 14","Space World 15",
		"Space World 16","Pokemon Festa","Pokemon Festa 06",
		"Pokemon Festa 07","Pokemon Festa 08","Pokemon Festa 09",
		"Pokemon Festa 10","Pokemon Festa 11","Pokemon Festa 12",
		"Pokemon Festa 13","Pokemon Festa 14","Pokemon Festa 15",
		"Pokemon Festa 16","PokePARK","PokePARK 06",
		"PokePARK 07","PokePARK 08","PokePARK 09",
		"PokePARK 10","PokePARK 11","PokePARK 12",
		"PokePARK 13","PokePARK 14","PokePARK 15",
		"PokePARK 16","Pokemon Center","PC Tokyo",
		"PC Osaka","PC Fukuoka","PC Nagoya",
		"PC Sapporo","PC Yokohama","Nintendo World",
		"Pokemon Event","Pokemon Event 06","Pokemon Event 07",
		"Pokemon Event 08","Pokemon Event 09","Pokemon Event 10",
		"Pokemon Event 11","Pokemon Event 12","Pokemon Event 13",
		"Pokemon Event 14","Pokemon Event 15","Pokemon Event 16",
		"Wi-Fi Event","Wi-Fi Gift","Pokemon Fan Club",
		"Event Site","Concert Event"
	};

	const unsigned char movepp[] = {
		0,35,25,10,15,20,20,15,15,15,35,30,5,10,30,30,
		35,35,20,15,20,20,15,20,30,5,25,15,15,15,25,20,
		5,35,15,20,20,20,15,30,35,20,20,30,25,40,20,15,
		20,20,20,30,25,15,30,25,5,15,10,5,20,20,20,5,
		35,20,25,20,20,20,15,25,15,10,40,25,10,35,30,15,
		20,40,10,15,30,15,20,10,15,10,5,10,10,25,10,20,
		40,30,30,20,20,15,10,40,15,10,30,20,20,10,40,40,
		20,30,30,20,30,10,10,20,5,10,30,20,20,20,5,15,
		10,20,15,15,35,20,15,10,20,30,15,40,20,15,10,5,
		10,30,10,15,20,15,40,40,10,5,15,10,10,10,15,30,
		30,10,10,20,10,1,1,10,10,10,5,15,25,15,10,15,
		30,5,40,15,10,25,10,30,10,20,10,10,10,10,10,20,
		5,40,5,5,15,5,10,5,15,10,10,10,20,20,40,15,
		10,20,20,25,5,15,10,5,20,15,20,25,20,5,30,5,
		10,20,40,5,20,40,20,15,35,10,5,5,5,15,5,20,
		5,5,15,20,10,5,5,15,15,15,15,10,10,10,20,10,
		10,10,10,15,15,15,10,20,20,10,20,20,20,20,20,10,
		10,10,20,20,5,15,10,10,15,10,20,5,5,10,10,20,
		5,10,20,10,20,20,20,5,5,15,20,10,15,20,15,10,
		10,15,10,5,5,10,15,10,5,20,25,5,40,10,5,40,
		15,20,20,5,15,20,30,15,15,5,10,30,20,30,15,5,
		40,15,5,20,5,15,25,40,15,20,15,20,15,20,10,20,
		20,5,5,10,5,40,10,10,5,10,10,15,10,20,30,30,
		10,20,5,10,10,15,10,10,5,15,5,10,10,30,20,20,
		10,10,5,5,10,5,20,10,20,10,15,10,20,20,20,15,
		15,10,15,20,15,10,10,10,20,5,30,5,10,15,10,10,
		5,20,30,10,30,15,15,15,15,30,10,20,15,10,10,20,
		15,5,5,15,15,5,10,5,20,5,15,20,5,20,20,20,20,10,
		20,10,15,20,15,10,10,5,10,5,5,10,5,5,10,5,5,5,
	};

	const char *movelist[] = { "(none)",
		"Pound","Karate Chop","DoubleSlap","Comet Punch","Mega Punch",
		"Pay Day","Fire Punch","Ice Punch","ThunderPunch","Scratch",
		"ViceGrip","Guillotine","Razor Wind","Swords Dance","Cut",
		"Gust","Wing Attack","Whirlwind","Fly","Bind",
		"Slam","Vine Whip","Stomp","Double Kick","Mega Kick",
		"Jump Kick","Rolling Kick","Sand-Attack","Headbutt","Horn Attack",
		"Fury Attack","Horn Drill","Tackle","Body Slam","Wrap",
		"Take Down","Thrash","Double-Edge","Tail Whip","Poison Sting",
		"Twineedle","Pin Missile","Leer","Bite","Growl",
		"Roar","Sing","Supersonic","SonicBoom","Disable",
		"Acid","Ember","Flamethrower","Mist","Water Gun",
		"Hydro Pump","Surf","Ice Beam","Blizzard","Psybeam",
		"BubbleBeam","Aurora Beam","Hyper Beam","Peck","Drill Peck",
		"Submission","Low Kick","Counter","Seismic Toss","Strength",
		"Absorb","Mega Drain","Leech Seed","Growth","Razor Leaf",
		"SolarBeam","PoisonPowder","Stun Spore","Sleep Powder","Petal Dance",
		"String Shot","Dragon Rage","Fire Spin","ThunderShock","Thunderbolt",
		"Thunder Wave","Thunder","Rock Throw","Earthquake","Fissure",
		"Dig","Toxic","Confusion","Psychic","Hypnosis",
		"Meditate","Agility","Quick Attack","Rage","Teleport",
		"Night Shade","Mimic","Screech","Double Team","Recover",
		"Harden","Minimize","SmokeScreen","Confuse Ray","Withdraw",
		"Defense Curl","Barrier","Light Screen","Haze","Reflect",
		"Focus Energy","Bide","Metronome","Mirror Move","Selfdestruct",
		"Egg Bomb","Lick","Smog","Sludge","Bone Club",
		"Fire Blast","Waterfall","Clamp","Swift","Skull Bash",
		"Spike Cannon","Constrict","Amnesia","Kinesis","Softboiled",
		"Hi Jump Kick","Glare","Dream Eater","Poison Gas","Barrage",
		"Leech Life","Lovely Kiss","Sky Attack","Transform","Bubble",
		"Dizzy Punch","Spore","Flash","Psywave","Splash",
		"Acid Armor","Crabhammer","Explosion","Fury Swipes","Bonemerang",
		"Rest","Rock Slide","Hyper Fang","Sharpen","Conversion",
		"Tri Attack","Super Fang","Slash","Substitute","Struggle",
		"Sketch","Triple Kick","Thief","Spider Web","Mind Reader",
		"Nightmare","Flame Wheel","Snore","Curse","Flail",
		"Conversion2","Aeroblast","Cotton Spore","Reversal","Spite",
		"Powder Snow","Protect","Mach Punch","Scary Face","Faint Attack",
		"Sweet Kiss","Belly Drum","Sludge Bomb","Mud-Slap","Octazooka",
		"Spikes","Zap Cannon","Foresight","Destiny Bond","Perish Song",
		"Icy Wind","Detect","Bone Rush","Lock-On","Outrage",
		"Sandstorm","Giga Drain","Endure","Charm","Rollout",
		"False Swipe","Swagger","Milk Drink","Spark","Fury Cutter",
		"Steel Wing","Mean Look","Attract","Sleep Talk","Heal Bell",
		"Return","Present","Frustration","Safeguard","Pain Split",
		"Sacred Fire","Magnitude","DynamicPunch","Megahorn","DragonBreath",
		"Baton Pass","Encore","Pursuit","Rapid Spin","Sweet Scent",
		"Iron Tail","Metal Claw","Vital Throw","Morning Sun","Synthesis",
		"Moonlight","Hidden Power","Cross Chop","Twister","Rain Dance",
		"Sunny Day","Crunch","Mirror Coat","Psych Up","ExtremeSpeed",
		"AncientPower","Shadow Ball","Future Sight","Rock Smash","Whirlpool",
		"Beat Up","Fake Out","Uproar","Stockpile","Spit Up",
		"Swallow","Heat Wave","Hail","Torment","Flatter",
		"Will-O-Wisp","Memento","Facade","Focus Punch","SmellingSalt",
		"Follow Me","Nature Power","Charge","Taunt","Helping Hand",
		"Trick","Role Play","Wish","Assist","Ingrain",
		"Superpower","Magic Coat","Recycle","Revenge","Brick Break",
		"Yawn","Knock Off","Endeavor","Eruption","Skill Swap",
		"Imprison","Refresh","Grudge","Snatch","Secret Power",
		"Dive","Arm Thrust","Camouflage","Tail Glow","Luster Purge",
		"Mist Ball","FeatherDance","Teeter Dance","Blaze Kick","Mud Sport",
		"Ice Ball","Needle Arm","Slack Off","Hyper Voice","Poison Fang",
		"Crush Claw","Blast Burn","Hydro Cannon","Meteor Mash","Astonish",
		"Weather Ball","Aromatherapy","Fake Tears","Air Cutter","Overheat",
		"Odor Sleuth","Rock Tomb","Silver Wind","Metal Sound","GrassWhistle",
		"Tickle","Cosmic Power","Water Spout","Signal Beam","Shadow Punch",
		"Extrasensory","Sky Uppercut","Sand Tomb","Sheer Cold","Muddy Water",
		"Bullet Seed","Aerial Ace","Icicle Spear","Iron Defense","Block",
		"Howl","Dragon Claw","Frenzy Plant","Bulk Up","Bounce",
		"Mud Shot","Poison Tail","Covet","Volt Tackle","Magical Leaf",
		"Water Sport","Calm Mind","Leaf Blade","Dragon Dance","Rock Blast",
		"Shock Wave","Water Pulse","Doom Desire","Psycho Boost","Roost",
		"Gravity","Miracle Eye","Wake-Up Slap","Hammer Arm","Gyro Ball",
		"Healing Wish","Brine","Natural Gift","Feint","Pluck",
		"Tailwind","Acupressure","Metal Burst","U-Turn","Close Combat",
		"Payback","Assurance","Embargo","Fling","Psycho Shift",
		"Trump Card","Heal Block","Wring Out","Power Trick","Gastro Acid",
		"Lucky Chant","Me First","Copycat","Power Swap","Guard Swap",
		"Punishment","Last Resort","Worry Seed","Sucker Punch","Toxic Spikes",
		"Heart Swap","Aqua Ring","Magnet Rise","Flare Blitz","Force Palm",
		"Aura Sphere","Rock Polish","Poison Jab","Dark Pulse","Night Slash",
		"Aqua Tail","Seed Bomb","Air Slash","X-Scissor","Bug Buzz",
		"Dragon Pulse","Dragon Rush","Power Gem","Drain Punch","Vacuum Wave",
		"Focus Blast","Energy Ball","Brave Bird","Earth Power","Switcheroo",
		"Giga Impact","Nasty Plot","Bullet Punch","Avalanche","Ice Shard",
		"Shadow Claw","Thunder Fang","Ice Fang","Fire Fang","Shadow Sneak",
		"Mud Bomb","Psycho Cut","Zen Headbutt","Mirror Shot","Flash Cannon",
		"Rock Climb","Defog","Trick Room","Draco Meteor","Discharge",
		"Lava Plume","Leaf Storm","Power Whip","Rock Wrecker","Cross Poison",
		"Gunk Shot","Iron Head","Magnet Bomb","Stone Edge","Captivate",
		"Stealth Rock","Grass Knot","Chatter","Judgment","Bug Bite",
		"Charge Beam","Wood Hammer","Aqua Jet","Attack Order","Defend Order",
		"Heal Order","Head Smash","Double Hit","Roar Of Time","Spacial Rend",
		"Lunar Dance","Crush Grip","Magma Storm","Dark Void","Seed Flare",
		"Ominous Wind","Shadow Force"
	};


	const char *species[] = { "???",
		"Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon","Charizard",
		"Squirtle","Wartortle","Blastoise","Caterpie","Metapod","Butterfree",
		"Weedle","Kakuna","Beedrill","Pidgey","Pidgeotto","Pidgeot",
		"Rattata","Raticate","Spearow","Fearow","Ekans","Arbok",
		"Pikachu","Raichu","Sandshrew","Sandslash","Nidoran♀","Nidorina",
		"Nidoqueen","Nidoran♂","Nidorino","Nidoking","Clefairy","Clefable",
		"Vulpix","Ninetales","Jigglypuff","Wigglytuff","Zubat","Golbat",
		"Oddish","Gloom","Vileplume","Paras","Parasect","Venonat",
		"Venomoth","Diglett","Dugtrio","Meowth","Persian","Psyduck",
		"Golduck","Mankey","Primeape","Growlithe","Arcanine","Poliwag",
		"Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam","Machop",
		"Machoke","Machamp","Bellsprout","Weepinbell","Victreebel","Tentacool",
		"Tentacruel","Geodude","Graveler","Golem","Ponyta","Rapidash",
		"Slowpoke","Slowbro","Magnemite","Magneton","Farfetch'd","Doduo",
		"Dodrio","Seel","Dewgong","Grimer","Muk","Shellder",
		"Cloyster","Gastly","Haunter","Gengar","Onix","Drowzee",
		"Hypno","Krabby","Kingler","Voltorb","Electrode","Exeggcute",
		"Exeggutor","Cubone","Marowak","Hitmonlee","Hitmonchan","Lickitung",
		"Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela",
		"Kangaskhan","Horsea","Seadra","Goldeen","Seaking","Staryu",
		"Starmie","Mr. Mime","Scyther","Jynx","Electabuzz","Magmar",
		"Pinsir","Tauros","Magikarp","Gyarados","Lapras","Ditto","Eevee",
		"Vaporeon","Jolteon","Flareon","Porygon","Omanyte","Omastar",
		"Kabuto","Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos",
		"Moltres","Dratini","Dragonair","Dragonite","Mewtwo","Mew",

		"Chikorita","Bayleef","Meganium","Cyndaquil","Quilava",
		"Typhlosion","Totodile","Croconaw","Feraligatr","Sentret","Furret",
		"HootHoot","Noctowl","Ledyba","Ledian","Spinarak","Ariados",
		"Crobat","Chinchou","Lanturn","Pichu","Cleffa","Igglybuff",
		"Togepi","Togetic","Natu","Xatu","Mareep","Flaaffy",
		"Ampharos","Bellossom","Marill","Azumarill","Sudowoodo","Politoed",
		"Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora",
		"Yanma","Wooper","Quagsire","Espeon","Umbreon","Murkrow",
		"Slowking","Misdreavus","Unown","Wobbuffet","Girafarig","Pineco",
		"Forretress","Dunsparce","Gligar","Steelix","Snubbull","Granbull",
		"Qwilfish","Scizor","Shuckle","Heracross","Sneasel","Teddiursa",
		"Ursaring","Slugma","Magcargo","Swinub","Piloswine","Corsola",
		"Remoraid","Octillery","Delibird","Mantine","Skarmory","Houndour",
		"Houndoom","Kingdra","Phanpy","Donphan","Porygon2","Stantler",
		"Smeargle","Tyrogue","Hitmontop","Smoochum","Elekid","Magby",
		"Miltank","Blissey","Raikou","Entei","Suicune","Larvitar",
		"Pupitar","Tyranitar","Lugia","Ho-oh","Celebi",

		"Treecko","Grovyle","Sceptile","Torchic","Combusken","Blaziken",
		"Mudkip","Marshtomp","Swampert","Poochyena","Mightyena",
		"Zigzagoon","Linoone","Wurmple","Silcoon","Beautifly",
		"Cascoon","Dustox","Lotad","Lombre","Ludicolo","Seedot",
		"Nuzleaf","Shiftry","Taillow","Swellow","Wingull","Pelipper",
		"Ralts","Kirlia","Gardevoir","Surskit","Masquerain","Shroomish",
		"Breloom","Slakoth","Vigoroth","Slaking","Nincada","Ninjask",
		"Shedinja","Whismur","Loudred","Exploud","Makuhita","Hariyama",
		"Azurill","Nosepass","Skitty","Delcatty","Sableye","Mawile",
		"Aron","Lairon","Aggron","Meditite","Medicham","Electrike",
		"Manectric","Plusle","Minun","Volbeat","Illumise","Roselia",
		"Gulpin","Swalot","Carvanha","Sharpedo","Wailmer","Wailord",
		"Numel","Camerupt","Torkoal","Spoink","Grumpig","Spinda",
		"Trapinch","Vibrava","Flygon","Cacnea","Cacturne","Swablu",
		"Altaria","Zangoose","Seviper","Lunatone","Solrock","Barboach",
		"Whiscash","Corphish","Crawdaunt","Baltoy","Claydol","Lileep",
		"Cradily","Anorith","Armaldo","Feebas","Milotic","Castform",
		"Kecleon","Shuppet","Banette","Duskull","Dusclops","Tropius",
		"Chimecho","Absol","Wynaut","Snorunt","Glalie","Spheal","Sealeo",
		"Walrein","Clamperl","Huntail","Gorebyss","Relicanth","Luvdisc",
		"Bagon","Shelgon","Salamence","Beldum","Metang","Metagross",
		"Regirock","Regice","Registeel","Latias","Latios","Kyogre",
		"Groudon","Rayquaza","Jirachi","Deoxys",

		"Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape",
		"Piplup","Prinplup","Empoleon","Starly","Staravia","Staraptor",
		"Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio",
		"Luxray","Budew","Roserade","Cranidos","Rampardos","Shieldon",
		"Bastiodon","Burmy","Wormadam","Mothim","Combee","Vespiquen",
		"Pachirisu","Buizel","Floatzel","Cherubi","Cherrim","Shellos",
		"Gastrodon","Ambipom","Drifloon","Drifblim","Buneary","Lopunny",
		"Mismagius","Honchkrow","Glameow","Purugly","Chingling","Stunky",
		"Skuntank","Bronzor","Bronzong","Bonsly","Mime Jr.","Happiny",
		"Chatot","Spiritomb","Gible","Gabite","Garchomp","Munchlax","Riolu",
		"Lucario","Hippopotas","Hippowdon","Skorupi","Drapion","Croagunk",
		"Toxicroak","Carnivine","Finneon","Lumineon","Mantyke","Snover",
		"Abomasnow","Weavile","Magnezone","Lickilicky","Rhyperior","Tangrowth",
		"Electivire","Magmortar","Togekiss","Yanmega","Leafeon","Glaceon",
		"Gliscor","Mamoswine","Porygon-Z","Gallade","Probopass","Dusknoir",
		"Froslass","Rotom","Uxie","Mesprit","Azelf","Dialga","Palkia",
		"Heatran","Regigigas","Giratina","Cresselia","Phione","Manaphy",
		"Darkrai","Shaymin","Arceus"
	};
}

#endif /* __DATA_TABLES_H__ */
